from enum import Enum

class Tok_Type(Enum):
    """ Class representing all token types generated by the lexer. """
    # Atom types
    STRING = auto()
    ID = auto()
    BOOL = auto()
    NUM = auto()

    COMMA = auto()
    # Single quote '
    QUOTE = auto()
    # Double quote "
    DQUOTE = auto()
    LRBRACE = auto()
    RRBRALE = auto()
    LSBRACE = auto()
    RSBRACE = auto()
    # Comparison op
    EQ = auto()
    NEQ = auto
    LT = auto()
    GT = auto()
    LTE = auto()
    GTE = auto()

    # arith op
    PLUS = auto()
    MINUS = auto()
    DIV = auto()
    MUL = auto()

    # Boolean op
    BANG = auto()
    TRUE = auto()
    FALSE = auto()
    AND = auto()
    OR = auto()

    FUNC = auto()
    ASSIGN = auto()
    EOF = auto()

class Token:
    def __init__(self, tok_type, literal=None):
        self.tok_type = tok_type
        self.literal = literal
